### ISSUE TITLE
Adding icon to the web-app

### ISSUE THREAD

**Issue by BahauddinAziz** [BahauddinAziz/trusues#3]
The web-app is missing an icon. So can I add that.

**Comment by BahauddinAziz** [comment]
ok, so do you have an icon already?

**Comment by SomBold** [comment]
Yes I do have two icons.
![Favicon1](https://user-images.githubusercontent.com/55487672/82847840-ff9b9900-9f0d-11ea-9b5b-a95609fbd798.png)
![Favicon 2](https://user-images.githubusercontent.com/55487672/82847853-0aeec480-9f0e-11ea-9c6f-dd02a57df275.png)

**Comment by BahauddinAziz** [comment]
OK, so just add one of these,
Till we get a logo
